
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,full_name TEXT,status TEXT DEFAULT 'active',is_superadmin INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS organizations(id TEXT PRIMARY KEY,name TEXT NOT NULL,slug TEXT UNIQUE NOT NULL,owner_user_id TEXT,billing_email TEXT,status TEXT DEFAULT 'active',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS organization_members(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,role TEXT NOT NULL,status TEXT DEFAULT 'active',created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(tenant_id,user_id));
CREATE TABLE IF NOT EXISTS plans(id TEXT PRIMARY KEY,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,description TEXT,price_amount REAL DEFAULT 0,price_currency TEXT DEFAULT 'RUB',billing_period TEXT DEFAULT 'month',included_goe REAL DEFAULT 0,limits TEXT DEFAULT '{}',features TEXT DEFAULT '{}',is_active INTEGER DEFAULT 1,sort_order INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS subscriptions(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,plan_id TEXT NOT NULL,status TEXT NOT NULL,provider TEXT,provider_subscription_id TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS goe_accounts(id TEXT PRIMARY KEY,tenant_id TEXT UNIQUE NOT NULL,balance REAL DEFAULT 0,reserved_balance REAL DEFAULT 0,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS goe_ledger_entries(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,account_id TEXT NOT NULL,entry_type TEXT NOT NULL,amount REAL NOT NULL,balance_after REAL NOT NULL,reference_type TEXT,reference_id TEXT,idempotency_key TEXT,description TEXT,metadata TEXT DEFAULT '{}',created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(tenant_id,idempotency_key));
CREATE TABLE IF NOT EXISTS bots(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,telegram_bot_id INTEGER UNIQUE,username TEXT,display_name TEXT,encrypted_token TEXT NOT NULL,token_fingerprint TEXT NOT NULL,webhook_secret TEXT UNIQUE NOT NULL,webhook_url TEXT,status TEXT DEFAULT 'draft',last_update_at TEXT,last_error TEXT,created_by_user_id TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS bot_configs(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,bot_id TEXT NOT NULL,language TEXT DEFAULT 'ru',tone_of_voice TEXT,brand_description TEXT,system_prompt TEXT,welcome_message TEXT,fallback_message TEXT,content_rules TEXT DEFAULT '{}',safety_rules TEXT DEFAULT '{}',generation_limits TEXT DEFAULT '{}',store_enabled INTEGER DEFAULT 1,analytics_enabled INTEGER DEFAULT 1,is_active INTEGER DEFAULT 1,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(tenant_id,bot_id));
CREATE TABLE IF NOT EXISTS products(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,category_id TEXT,sku TEXT,name TEXT NOT NULL,slug TEXT NOT NULL,description TEXT,short_description TEXT,price_amount REAL NOT NULL,currency TEXT DEFAULT 'RUB',stock_quantity INTEGER,stock_policy TEXT DEFAULT 'track',status TEXT DEFAULT 'draft',attributes TEXT DEFAULT '{}',metadata TEXT DEFAULT '{}',created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(tenant_id,slug),UNIQUE(tenant_id,sku));
CREATE TABLE IF NOT EXISTS customers(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,telegram_user_id INTEGER,name TEXT,phone TEXT,email TEXT,metadata TEXT DEFAULT '{}',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,customer_id TEXT,bot_id TEXT,order_number TEXT NOT NULL,status TEXT DEFAULT 'draft',subtotal_amount REAL DEFAULT 0,total_amount REAL DEFAULT 0,currency TEXT DEFAULT 'RUB',customer_snapshot TEXT DEFAULT '{}',delivery_snapshot TEXT DEFAULT '{}',created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(tenant_id,order_number));
CREATE TABLE IF NOT EXISTS order_items(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,order_id TEXT NOT NULL,product_id TEXT,product_snapshot TEXT NOT NULL,quantity INTEGER NOT NULL,unit_price_amount REAL NOT NULL,total_amount REAL NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS content_generations(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,bot_id TEXT,request_source TEXT NOT NULL,content_type TEXT NOT NULL,prompt TEXT NOT NULL,status TEXT DEFAULT 'queued',result TEXT,error_message TEXT,goe_cost REAL DEFAULT 0,idempotency_key TEXT,completed_at TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(tenant_id,idempotency_key));
CREATE TABLE IF NOT EXISTS analytics_events(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,bot_id TEXT,user_id TEXT,event_name TEXT NOT NULL,entity_type TEXT,entity_id TEXT,properties TEXT DEFAULT '{}',occurred_at TEXT DEFAULT CURRENT_TIMESTAMP,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS payments(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,subscription_id TEXT,provider TEXT NOT NULL,provider_payment_id TEXT,amount REAL NOT NULL,currency TEXT DEFAULT 'RUB',status TEXT NOT NULL,metadata TEXT DEFAULT '{}',created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(provider,provider_payment_id));
CREATE INDEX IF NOT EXISTS idx_members_user ON organization_members(user_id); CREATE INDEX IF NOT EXISTS idx_bots_tenant ON bots(tenant_id); CREATE INDEX IF NOT EXISTS idx_products_tenant ON products(tenant_id,status); CREATE INDEX IF NOT EXISTS idx_events_tenant ON analytics_events(tenant_id,occurred_at DESC);
